name: flutter_thuchanh_08
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  intl: ^0.17.0
  modal_progress_hud_nsn: ^0.5.0
  loading_animation_widget: ^1.2.1
  form_field_validator: ^1.1.0
  loading_btn: ^1.0.3
  http: ^1.2.1
  provider: ^6.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
